[tool.poetry]
name = "fluentogram"
version = "1.0.28"
description = "A proper way to use an i18n mechanism with Aiogram3."
authors = ["Aleks"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
fluent-compiler = "^0.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
