[tool.poetry]
name = "fluentogram"
version = "1.1.2"
description = "A proper way to use an i18n mechanism with Aiogram3."
authors = ["Aleks"]
license = "MIT"

[tool.poetry.scripts]
i18n = 'fluentogram.cli:cli'

[tool.poetry.dependencies]
python = "^3.9"
fluent-compiler = "^0.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"
